version: "3.4"
services:
  asterisk:
    image: ast_mongo-asterisk:16.0.0
    container_name: asterisk
    restart: always
    privileged: true
    tty: true
    build:
      context: ./asterisk/
      dockerfile: Dockerfile
      args:
        VERSION_ASTERISK: 16.0.0
        VERSION_MONGOC: 1.17.5
        VERSION_LIBSRTP: 2.1.0
        DATABASE_HOST: mongodb+srv://sankalp:sankalp27@cluster0.eqbpw.mongodb.net
        DATABASE_NAME: asterisk
    network_mode: "host"
    volumes:
      - /var/log/asterisk:/var/log/asterisk
      - /var/asterisk/recording:/var/spool/asterisk/recording
  nodejs:
    image: node
    restart: always
    container_name: node_server
    ports:
      - "3000:3000"
    command: npm run dev
    build:
      context: ./core-server
      dockerfile: Dockerfile
    volumes:
      - ./core-server:/usr/src/app
  asterisk-ari:
    image: node
    container_name: asterisk-ari
    network_mode: "host"
    restart: always
    ports:
      - "4000:4000"
    command: npm run dev
    build:
      context: ./asterisk-ari
      dockerfile: Dockerfile
    volumes:
      - ./asterisk-ari:/usr/src/app
    depends_on:
      - asterisk
