version: '3'
services:
  mongo:
    image: mongo
    container_name: ast_mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
  asterisk:
    image: ast_mongo-asterisk:16.0.0
    container_name: asterisk
    build:
      ports:
        - "5060:5060"
        - "10000-10005:10000-10005/udp"
      context: ./asterisk/
      dockerfile: Dockerfile
      args:
        VERSION_ASTERISK: 16.0.0
        VERSION_MONGOC: 1.13.0
        VERSION_LIBSRTP: 2.1.0
        DATABASE_HOST: mongodb://ast_mongo:27017
        DATABASE_NAME: asterisk
  nodejs:
    image: node
    container_name: node_server
    ports:
      - "80:80"
    command: npm run start
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        DATABASE_HOST: mongodb://ast_mongo:27017
        DATABASE_NAME: asterisk

