version: '3'
services:
  asterisk:
    image: ast_mongo-asterisk:16.0.0
    container_name: asterisk
    ports:
      - "5060:5060"
    build:
      context: ./asterisk/
      dockerfile: Dockerfile
      args:
        VERSION_ASTERISK: 16.0.0
        VERSION_MONGOC: 1.13.0
        VERSION_LIBSRTP: 2.1.0
        DATABASE_HOST: mongodb+srv://sankalp:sankalp27@cluster0.eqbpw.mongodb.net/asterisk
        DATABASE_NAME: asterisk
  nodejs:
    image: node
    container_name: node_server
    ports:
      - "3000:3000"
    command: npm run dev
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app