version: '3.4'
services:
  asterisk:
    image: ast_mongo-asterisk:16.0.0
    container_name: asterisk
    privileged: true
    tty: true
    build:
      context: ./asterisk/
      dockerfile: Dockerfile
      args:
        VERSION_ASTERISK: 16.0.0
        VERSION_MONGOC: 1.13.0
        VERSION_LIBSRTP: 2.1.0
        DATABASE_HOST: mongodb://sankalp:sankalp27@cluster0-shard-00-00.eqbpw.mongodb.net:27017,cluster0-shard-00-02.eqbpw.mongodb.net:27017,cluster0-shard-00-01.eqbpw.mongodb.net:27017/asterisk?authSource=admin&replicaSet=atlas-10sic2-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
        DATABASE_NAME: asterisk
    network_mode: "host"
  nodejs:
    image: node
    container_name: node_server
    ports:
      - "3000:3000"
    command: npm run dev
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app