version: '3.4'
services:
  asterisk:
    image: ast_mongo-asterisk:16.0.0
    container_name: asterisk
    privileged: true
    tty: true
    build:
      context: ./asterisk/
      dockerfile: Dockerfile
      args:
        VERSION_ASTERISK: 16.0.0
        VERSION_MONGOC: 1.17.5
        VERSION_LIBSRTP: 2.1.0
        DATABASE_HOST: mongodb+srv://sankalp:sankalp27@cluster0.eqbpw.mongodb.net/asterisk
        DATABASE_NAME: asterisk
    network_mode: "host"
  nodejs:
    image: node
    container_name: node_server
    ports:
      - "3000:3000"
    command: npm run dev
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app